In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# Check the size of the dataset
print("Dataset shape:", df.shape)

# Check column names
print("\nColumn names:")
print(df.columns.tolist())

# Check data types
print("\nData types:")
print(df.dtypes)

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (891, 12)

Column names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Duplicate rows: 0

## 2. Initial Findings

The dataset contains 891 rows and 12 columns.

The initial inspection identified missing values in three columns:

- Age: 177 missing values
- Cabin: 687 missing values
- Embarked: 2 missing values

No duplicate rows were identified.

Most columns have appropriate data types. Numerical variables such as Age and Fare are stored as numeric types, while categorical/text variables such as Sex, Cabin, and Embarked are stored as object types.

### Cleaning Plan

- Age: Missing values will be replaced using the median age because Age is a numerical variable and the median is less affected by extreme values.
- Cabin: The column has a very high proportion of missing values. Instead of inventing cabin numbers, missing values will be represented as "Unknown".
- Embarked: The two missing values will be filled using the mode because Embarked is a categorical variable.
- Duplicate rows: No duplicates were found, so no rows will be removed.

In [3]:
# Calculate the median age
median_age = df["Age"].median()

print("Median age:", median_age)

Median age: 28.0

In [4]:
# Fill missing Age values with the median age
df["Age"] = df["Age"].fillna(median_age)

# Verify that Age has no missing values
print("Missing Age values after cleaning:", df["Age"].isnull().sum())

Missing Age values after cleaning: 0

In [5]:
# Replace missing Cabin values with "Unknown"
df["Cabin"] = df["Cabin"].fillna("Unknown")

# Verify that Cabin has no missing values
print("Missing Cabin values after cleaning:", df["Cabin"].isnull().sum())

Missing Cabin values after cleaning: 0

In [6]:
# Find the most frequent Embarked value
embarked_mode = df["Embarked"].mode()[0]

print("Most frequent Embarked value:", embarked_mode)

Most frequent Embarked value: S

In [7]:
# Fill missing Embarked values with the mode
df["Embarked"] = df["Embarked"].fillna(embarked_mode)

# Verify that Embarked has no missing values
print("Missing Embarked values after cleaning:", df["Embarked"].isnull().sum())

Missing Embarked values after cleaning: 0

In [8]:
# Check missing values after cleaning
print("Missing values after cleaning:")
print(df.isnull().sum())

# Check duplicate rows again
print("\nDuplicate rows after cleaning:", df.duplicated().sum())

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate rows after cleaning: 0

In [9]:
# Check data types after cleaning
print("Data types after cleaning:")
print(df.dtypes)

Data types after cleaning:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
# Check numerical columns for unusual values

print("Age range:", df["Age"].min(), "to", df["Age"].max())
print("Fare range:", df["Fare"].min(), "to", df["Fare"].max())
print("Pclass values:", sorted(df["Pclass"].unique()))
print("Survived values:", sorted(df["Survived"].unique()))
print("SibSp range:", df["SibSp"].min(), "to", df["SibSp"].max())
print("Parch range:", df["Parch"].min(), "to", df["Parch"].max())

Age range: 0.42 to 80.0
Fare range: 0.0 to 512.3292
Pclass values: [np.int64(1), np.int64(2), np.int64(3)]
Survived values: [np.int64(0), np.int64(1)]
SibSp range: 0 to 8
Parch range: 0 to 6

In [11]:
# Final validation of the cleaned dataset

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows of cleaned data:")
display(df.head())

Dataset shape: (891, 12)

Missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate rows: 0

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

First 5 rows of cleaned data:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [12]:
# Save the cleaned dataset
df.to_csv("cleaned_titanic.csv", index=False)

print("Cleaned dataset saved successfully as cleaned_titanic.csv")

Cleaned dataset saved successfully as cleaned_titanic.csv

## 3. Data Cleaning Summary

The Titanic dataset was successfully cleaned and prepared for further analysis.

### Cleaning actions performed

| Issue | Action Taken |
|---|---|
| Missing Age values (177) | Replaced with the median age (28.0) |
| Missing Cabin values (687) | Replaced with "Unknown" |
| Missing Embarked values (2) | Replaced with the mode ("S") |
| Duplicate rows | No duplicates were found |
| Data types | Verified as appropriate for analysis |
| Numerical values | Checked for unusual or invalid ranges |

### Assumptions

1. The median was used for missing Age values because Age is numerical and the median is less sensitive to extreme values.
2. Missing Cabin values were represented as "Unknown" rather than assigning fabricated cabin information.
3. Missing Embarked values were replaced with the most frequent category, "S".
4. Existing data types were retained because they were suitable for analysis and future machine-learning applications.
5. No rows were removed because of missing values, as doing so would result in substantial data loss.

The cleaned dataset was saved as `cleaned_titanic.csv`.

In [13]:
# Confirm the cleaned dataset
print("Final dataset shape:", df.shape)
print("Cleaned dataset saved as: cleaned_titanic.csv")

Final dataset shape: (891, 12)
Cleaned dataset saved as: cleaned_titanic.csv